[pytest]
markers =
    test_index_route: Testing index routing
    test_init_doc
    test_embed_job_title
    test_embed_job_description
    get_request_reach_for_400
    get_request_reach_for_200
    get_request_be_reached_400
    get_request_be_reached_200
    get_request_bubble
    post_response_reach_for
    post_response_be_reached
    post_response_bubble
    get_suggestions

    test_distance_utility
    test_df_to_json_utility
    test_mongodb_connection_utility
    test_filter_location

    test_QNNAgent
    test_MABAgent
